groups:
- name: stocks-derived
  rules:
  - record: stock_price_change_1h_percent
    expr: (stock_price - stock_price offset 1h) / (stock_price offset 1h) * 100
  - record: stock_price_change_24h_percent
    expr: (stock_price - stock_price offset 24h) / (stock_price offset 24h) * 100
  - record: stock_price_ma_60m
    expr: avg_over_time(stock_price[60m])
  - record: stock_relative_strength_vs_spy
    expr: stock_price / ignoring(symbol) group_left() stock_price{symbol="SPY"} * 100

- name: stocks-alerts
  rules:
  - alert: StockDropFast1h
    expr: stock_price_change_1h_percent < -2
    for: 10m
    labels: { severity: warning }
    annotations:
      summary: "Rapid 1h drop for {{ .symbol }}"
      description: "Price is down {{ printf \"%.2f\"  }}% in 1h."

  - alert: StockDropDay
    expr: stock_price_change_24h_percent < -5
    for: 30m
    labels: { severity: critical }
    annotations:
      summary: "24h drop for {{ .symbol }}"
      description: "Down {{ printf \"%.2f\"  }}% in 24h."
